import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex justify-center items-center h-screen">
      <div className="container mx-auto flex text-primary w-full p-5 sm:p-10 justify-center items-center">
        <div className="flex-1 max-w-[450px] p-10 py-8 shadow-xl border min-h-[600px] relative bg-white">
          {children}
          <div className="hidden md:block absolute top-16 -left-20 rounded-md rounded-bl-none rounded-br-none bg-primary text-white p-2 px-8 -rotate-90 -z-10 font-semibold">
            Organick
          </div>
          <div className="absolute bottom-0 text-center left-1/2 -translate-x-1/2 my-5 ">
            Back to{" "}
            <Link href="/" className="font-bold underline">
              Home
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
